name: Release Beta to Play Store

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{secrets.SIGNING_KEY}}
          alias: ${{secrets.ALIAS}}
          keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
          keyPassword: ${{secrets.KEY_PASSWORD}}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{env.SIGNED_RELEASE_FILE}}

      - name: Deploy to Play Store (BETA)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT_JSON}}
          releaseFiles: app/build/outputs/bundle/release/*.aab
          packageName: com.foreverrafs.hypervid
          track: beta
          whatsNewDirectory: whatsnew/